package com.stokr.strategy;

import java.math.BigDecimal;

/**
 * Signal generated by a strategy plugin.
 * trailTriggerPct: % gain from entry that activates trailing stop (default 0.5)
 * trailDistancePct: % below peak for the trailing stop (default 0.3)
 */
public record Signal(
        String symbol,
        Side side,
        BigDecimal entryPrice,
        BigDecimal stopLoss,
        BigDecimal target,
        double confidence,
        String reason,
        double trailTriggerPct,
        double trailDistancePct
) {
    public enum Side { BUY, SELL }

    /** Convenience constructor — existing strategies use this, gets default trail params. */
    public Signal(String symbol, Side side, BigDecimal entryPrice, BigDecimal stopLoss,
                  BigDecimal target, double confidence, String reason) {
        this(symbol, side, entryPrice, stopLoss, target, confidence, reason, 0.5, 0.3);
    }

    public boolean isValid() {
        return symbol != null && !symbol.isBlank()
                && entryPrice != null && entryPrice.compareTo(BigDecimal.ZERO) > 0
                && stopLoss != null && target != null;
    }
}
