package com.stokr.strategy;

import java.math.BigDecimal;

/**
 * Signal generated by a strategy plugin.
 */
public record Signal(
        String symbol,
        Side side,
        BigDecimal entryPrice,
        BigDecimal stopLoss,
        BigDecimal target,
        double confidence,
        String reason
) {
    public enum Side { BUY, SELL }

    public boolean isValid() {
        return symbol != null && !symbol.isBlank()
                && entryPrice != null && entryPrice.compareTo(BigDecimal.ZERO) > 0
                && stopLoss != null && target != null;
    }
}
