package com.stokr.strategy.catalog;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestClient;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Commits a generated strategy template file to GitHub via the Contents API.
 * Enabled only when stokr.github.enabled=true and token/owner/repo are configured.
 *
 * Required env vars:
 *   STOKR_GITHUB_ENABLED=true
 *   STOKR_GITHUB_TOKEN=ghp_xxxx          (classic PAT or fine-grained with repo write)
 *   STOKR_GITHUB_OWNER=kvishnublr
 *   STOKR_GITHUB_REPO=stokr-platform
 *   STOKR_GITHUB_BRANCH=Release_v1       (defaults to main)
 */
@Service
@Slf4j
public class GitHubTemplateCommitService {

    private static final String GITHUB_API = "https://api.github.com";
    private static final String SOURCE_PATH_PREFIX = "stokr-strategy/src/main/java/com/stokr/strategy/generated/";

    @Value("${stokr.github.enabled:false}")
    private boolean enabled;

    @Value("${stokr.github.token:}")
    private String token;

    @Value("${stokr.github.owner:}")
    private String owner;

    @Value("${stokr.github.repo:}")
    private String repo;

    @Value("${stokr.github.branch:main}")
    private String branch;

    private final RestClient restClient = RestClient.builder()
            .baseUrl(GITHUB_API)
            .build();

    /**
     * Commits the given Java source content as a new file (or updates if it already exists)
     * in the GitHub repository under the generated strategy package path.
     *
     * @param className    Simple class name, e.g. TestCashSignalGenerator
     * @param javaContent  Full Java source to commit
     * @param strategyKey  Used in the commit message
     */
    public void commitTemplate(String className, String javaContent, String strategyKey) {
        if (!enabled) {
            log.debug("github.commit.skip reason=disabled");
            return;
        }
        if (token.isBlank() || owner.isBlank() || repo.isBlank()) {
            log.warn("github.commit.skip reason=missing_config owner={} repo={} tokenSet={}", owner, repo, !token.isBlank());
            return;
        }

        String filePath = SOURCE_PATH_PREFIX + className + ".java";
        String base64Content = Base64.getEncoder().encodeToString(javaContent.getBytes(StandardCharsets.UTF_8));
        String commitMessage = "feat: add strategy template " + strategyKey + "\n\nAuto-generated by Stokr admin panel via strategy catalog.";

        String existingSha = fetchExistingSha(filePath);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("message", commitMessage);
        body.put("content", base64Content);
        body.put("branch", branch);
        if (existingSha != null) {
            body.put("sha", existingSha);
        }

        try {
            restClient.put()
                    .uri("/repos/{owner}/{repo}/contents/{path}", owner, repo, filePath)
                    .header("Authorization", "Bearer " + token)
                    .header("Accept", "application/vnd.github+json")
                    .header("X-GitHub-Api-Version", "2022-11-28")
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(body)
                    .retrieve()
                    .toBodilessEntity();

            log.info("github.commit.success strategy={} file={} branch={} updated={}",
                    strategyKey, filePath, branch, existingSha != null);
        } catch (Exception e) {
            log.error("github.commit.failed strategy={} file={} error={}", strategyKey, filePath, e.getMessage());
            throw new RuntimeException("GitHub commit failed for " + filePath + ": " + e.getMessage(), e);
        }
    }

    @SuppressWarnings("unchecked")
    private String fetchExistingSha(String filePath) {
        try {
            Map<String, Object> response = restClient.get()
                    .uri("/repos/{owner}/{repo}/contents/{path}?ref={branch}", owner, repo, filePath, branch)
                    .header("Authorization", "Bearer " + token)
                    .header("Accept", "application/vnd.github+json")
                    .retrieve()
                    .body(Map.class);
            return response != null ? (String) response.get("sha") : null;
        } catch (HttpClientErrorException.NotFound e) {
            return null; // file doesn't exist yet — create it
        } catch (Exception e) {
            log.warn("github.sha_fetch.failed path={} error={}", filePath, e.getMessage());
            return null;
        }
    }
}
