import paramiko
s=paramiko.SSHClient();s.set_missing_host_key_policy(paramiko.AutoAddPolicy())
s.connect('173.249.55.84',username='root',password='`$SSH_PASSWORD',timeout=30)
def c(cmd):
    i,o,e = s.exec_command(cmd)
    return o.read().decode(errors='replace').strip()
print("=== Env files ===")
print(c("ls -la /root/stokr-platform/stokr-lite/.env 2>/dev/null || echo 'no .env'"))
print(c("ls -la /root/stokr-platform/.env 2>/dev/null || echo 'no root .env'"))
print(c("cat /root/stokr-platform/stokr-lite/.env 2>/dev/null || echo 'no stokr-lite .env'"))
print()
print("=== Git log for docker-compose ===")
print(c("cd /root/stokr-platform && git log --oneline -5 -- stokr-lite/docker-compose.yml 2>/dev/null"))
print()
print("=== Old compose (from git, before my change) ===")
print(c("cd /root/stokr-platform && git show HEAD~1:stokr-lite/docker-compose.yml 2>/dev/null | head -20 || echo 'cant show'"))
print()
print("=== Try connecting to postgres as postgres user ===")
print(c("su - postgres -c 'psql -c \"SELECT 1\"' 2>&1 | head -5"))
print()
print("=== Docker exec test ===")
print(c("docker exec stokr-lite-backend env | grep SPRING_DATASOURCE 2>/dev/null || echo 'container not running'"))
s.close()

