#!/bin/bash

echo ""
echo "================================================"
echo "  STOKR P0 STABILITY SPRINT - DEPLOYMENT START"
echo "================================================"
echo ""
echo "Starting stokr-bootstrap service..."
echo ""
echo "Service Details:"
echo "  - Port: 8080"
echo "  - Admin Dashboard: http://localhost:8080/admin/dashboard"
echo "  - API Base: http://localhost:8080/api/admin/diagnostics"
echo ""
echo "BUILD INFORMATION:"
echo "  - JAR File: stokr-bootstrap/target/stokr-bootstrap-1.0.0-SNAPSHOT.jar"
echo "  - Size: 85 MB"
echo "  - Built: 2026-06-05 17:16:46 IST"
echo ""
echo "Included Components:"
echo "  ✓ 11 Database Migrations (Flyway)"
echo "  ✓ 7 API Endpoints"
echo "  ✓ Admin Dashboard UI (6 tabs)"
echo "  ✓ 24 Java Classes (entities, services, repos)"
echo "  ✓ 2 Controllers (API + Dashboard)"
echo ""
echo "================================================"
echo "  STARTING SERVICE..."
echo "================================================"
echo ""

cd "$(dirname "$0")"
java -jar stokr-bootstrap/target/stokr-bootstrap-1.0.0-SNAPSHOT.jar

echo ""
echo "Service stopped."
