print("=" * 70)
print("CAN 5L GIVE 20K MONTHLY? -- HONEST MATH")
print("=" * 70)
print()
print("TARGET: Rs.20,000/month on Rs.5,00,000 capital")
print("That is 4% monthly = 48% annual (risk-free)")
print()

print("THE BRUTAL MATH:")
print("-" * 50)
print("  Each round-trip costs Rs.529 FIXED")
print("  (Entry: Rs.404 brokerage+STT+charges)")
print("  (Exit: Rs.125 brokerage+charges)")
print()
print("  To make Rs.20,000 net:")
print("  Need Rs.20,000 + costs = gross profit")
print()
print("  If 44 trades/month: costs = 44 x Rs.529 = Rs.23,276")
print("  Need gross: Rs.20,000 + Rs.23,276 = Rs.43,276")
print("  Gross per trade: Rs.43,276 / 44 = Rs.984")
print("  That needs 15.1 pts deviation per trade")
print()

print("IS 15PT DEVIATION AVAILABLE 44 TIMES?")
print("-" * 50)
print("  NIFTY: 4 expiry cycles/month, 5-7 opps each = 20-28 opps")
print("  BANKNIFTY: 1 cycle, 3-5 opps = 3-5 opps")
print("  Total unique opps: 23-33 per month")
print("  With 15pt+ deviation: maybe 5-10 per month")
print()
print("  WE NEED 44. WE HAVE 5-10.")
print("  SHORTFALL: 34-39 trades!")
print()

print("WHAT ABOUT FASTER TURNOVER?")
print("-" * 50)
print("  Hold 1 day: Gross Rs.325 - Costs Rs.529 = NEGATIVE Rs.204")
print("  Hold 2 days: Gross Rs.455 - Costs Rs.529 = NEGATIVE Rs.74")
print("  Hold 3 days: Gross Rs.585 - Costs Rs.529 = Rs.56 (0.01%)")
print("  Hold 4 days: Gross Rs.715 - Costs Rs.529 = Rs.186 (0.04%)")
print("  Hold 7 days: Gross Rs.862 - Costs Rs.529 = Rs.333 (0.07%)")
print()
print("  FASTER TURNOVER = LESS INCOME (costs eat the edge)")
print()

print("WHAT ABOUT INTRADAY?")
print("-" * 50)
print("  Enter 09:30 deviation=14, Exit 15:00 deviation=8")
print("  Gross: 6pts x 65 = Rs.390")
print("  Costs: Rs.529")
print("  Net: NEGATIVE Rs.139")
print()
print("  INTRADAY LOSES MONEY on parity break!")
print()

print("=" * 70)
print("HONEST ANSWER")
print("=" * 70)
print()
print("  Rs.5L -> Rs.20K/month = 4% monthly = IMPOSSIBLE")
print("  with pure parity break (risk-free)")
print()
print("  The math does not support it:")
print("  - Fixed costs of Rs.529 per trade")
print("  - Only 23-33 opps/month (not 44)")
print("  - Faster turnover reduces income (costs stay same)")
print("  - Intraday loses money")
print()

print("  REALISTIC MAX on Rs.5L:")
print("  - 3 positions x Rs.458 x 5 cycles = Rs.6,870/month")
print("  - That is 1.4% monthly = 16.5% annual")
print("  - THIS IS THE CEILING for risk-free on Rs.5L")
print()

print("  TO GET Rs.20K/month:")
print("  - Rs.15L capital (7-8 sets) = Rs.14-18K/month")
print("  - Rs.20L capital (10 sets) = Rs.18-23K/month")
print("  - Rs.25L capital (12 sets) = Rs.22-28K/month")
print()

print("  OR: Add low-risk strategies (not risk-free)")
print("  - Parity break: Rs.3L -> Rs.3-5K/month")
print("  - Calendar spread: Rs.2L -> Rs.2-4K/month")
print("  - Combined: Rs.5-9K/month on Rs.5L")
print("  - Still not Rs.20K, but better R:R")
print()
print("  THE TRUTH: Risk-free 4% monthly does not exist.")
print("  Risk-free returns are capped at 1-2% monthly.")
print("  To get 4%+ monthly, you MUST take some risk.")
