-- V94: Confidence-Based Dynamic Strategy System
-- Stores minute-by-minute confidence scores for all Nifty 100 stocks
-- Enables traders to select confidence threshold and auto-generate signals

-- 1. Store minute-by-minute confidence scores for all Nifty 100
CREATE TABLE IF NOT EXISTS confidence_scores (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    confidence_score INTEGER CHECK (confidence_score >= 0 AND confidence_score <= 100),
    buyer_pressure INTEGER CHECK (buyer_pressure >= 0 AND buyer_pressure <= 100),
    seller_pressure INTEGER CHECK (seller_pressure >= 0 AND seller_pressure <= 100),
    liquidity_score INTEGER CHECK (liquidity_score >= 0 AND liquidity_score <= 100),
    signal_strength VARCHAR(30),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_confidence_symbol_time
    ON confidence_scores(symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_confidence_score
    ON confidence_scores(confidence_score DESC);
CREATE INDEX IF NOT EXISTS idx_confidence_timestamp
    ON confidence_scores(timestamp DESC);
-- Index on symbol alone is covered by idx_confidence_symbol_time

-- 2. Trader configuration for confidence threshold
CREATE TABLE IF NOT EXISTS confidence_strategy_config (
    id SERIAL PRIMARY KEY,
    trader_id UUID NOT NULL,
    strategy_name VARCHAR(128) NOT NULL UNIQUE,
    min_confidence_threshold INTEGER NOT NULL CHECK (min_confidence_threshold IN (60, 70, 80, 90)),
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_config_trader
    ON confidence_strategy_config(trader_id);
CREATE INDEX IF NOT EXISTS idx_config_enabled
    ON confidence_strategy_config(enabled);
CREATE INDEX IF NOT EXISTS idx_config_threshold
    ON confidence_strategy_config(min_confidence_threshold);

-- 3. Daily rollup summary (signals by threshold)
CREATE TABLE IF NOT EXISTS confidence_signal_summary (
    id SERIAL PRIMARY KEY,
    summary_date DATE NOT NULL UNIQUE,
    threshold_60_count INTEGER DEFAULT 0,
    threshold_70_count INTEGER DEFAULT 0,
    threshold_80_count INTEGER DEFAULT 0,
    threshold_90_count INTEGER DEFAULT 0,
    threshold_60_targets INTEGER DEFAULT 0,
    threshold_70_targets INTEGER DEFAULT 0,
    threshold_80_targets INTEGER DEFAULT 0,
    threshold_90_targets INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_summary_date
    ON confidence_signal_summary(summary_date DESC);

-- 4. Comments for clarity
COMMENT ON TABLE confidence_scores IS
    'Minute-by-minute confidence scores for all Nifty 100 stocks from order flow analysis';
COMMENT ON COLUMN confidence_scores.confidence_score IS
    'Overall confidence score 0-100 based on order flow metrics';
COMMENT ON COLUMN confidence_scores.buyer_pressure IS
    'Buyer pressure score 0-100 from bid/ask ratio and volume analysis';

COMMENT ON TABLE confidence_strategy_config IS
    'Trader preferences for confidence threshold (60, 70, 80, 90)';
COMMENT ON COLUMN confidence_strategy_config.trader_id IS
    'UUID of the trader selecting this threshold';
COMMENT ON COLUMN confidence_strategy_config.strategy_name IS
    'Auto-generated strategy name: CONFIDENCE_BASED_{threshold}';

COMMENT ON TABLE confidence_signal_summary IS
    'Daily rollup of signals generated by threshold level';
