import { useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import client from '../api/client';

function AnimatedCounter({ value, duration = 1200 }) {
  const [display, setDisplay] = useState(0);
  useEffect(() => {
    let start = null;
    const animate = (ts) => {
      if (!start) start = ts;
      const p = Math.min((ts - start) / duration, 1);
      const eased = 1 - Math.pow(1 - p, 3);
      setDisplay(Math.floor(value * eased));
      if (p < 1) requestAnimationFrame(animate);
    };
    requestAnimationFrame(animate);
  }, [value, duration]);
  return <span>{display.toLocaleString('en-IN')}</span>;
}

export default function Signals() {
  const [filter, setFilter] = useState('ALL'); // ALL, GENERATED, EXECUTED, REJECTED, EXPIRED
  const [isLoggedIn, setIsLoggedIn] = useState(!!localStorage.getItem('token'));
  const [timeFilter, setTimeFilter] = useState('ALL'); // ALL, TODAY, HISTORY
  const [searchSymbol, setSearchSymbol] = useState('');

  const { data: signals = [], isLoading: sigLoading } = useQuery({
    queryKey: ['signals'],
    queryFn: async () => {
      const res = await client.get('/signals?t=' + Date.now());
      return res.data;
    },
    staleTime: 0,
    gcTime: 0,
    refetchOnWindowFocus: true,
  });

  const { data: stats = { total: 0, today: 0, active: 0 } } = useQuery({
    queryKey: ['signal-stats'],
    queryFn: async () => {
      const res = await client.get('/signals/stats');
      return res.data;
    },
  });

  const { data: positions = [] } = useQuery({
    queryKey: ['chartink-positions'],
    queryFn: async () => {
      const res = await client.get('/signals/positions');
      return res.data;
    },
  });

  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);

  const filtered = signals
    .filter(s => {
      if (filter !== 'ALL' && s.status !== filter) return false;
      if (searchSymbol && !s.symbol.toUpperCase().includes(searchSymbol.toUpperCase())) return false;

      const signalDate = new Date(s.createdAt);
      signalDate.setHours(0, 0, 0, 0);

      if (timeFilter === 'TODAY' && signalDate.getTime() !== todayStart.getTime()) return false;
      if (timeFilter === 'HISTORY' && signalDate.getTime() === todayStart.getTime()) return false;

      return true;
    })
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)); // Sort by newest first

  const statCards = [
    { label: 'Total Signals', value: stats.total, icon: '📡', gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)' },
    { label: 'Today', value: stats.today, icon: '📅', gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)' },
    { label: 'Active', value: stats.active, icon: '⚡', gradient: 'linear-gradient(135deg, #10b981, #059669)' },
  ];

  const statusColors = {
    GENERATED: { bg: 'rgba(99,102,241,0.12)', text: '#4f46e5', border: 'rgba(99,102,241,0.25)' },
    EXECUTED: { bg: 'rgba(16,185,129,0.12)', text: '#059669', border: 'rgba(16,185,129,0.25)' },
    REJECTED: { bg: 'rgba(244,63,94,0.12)', text: '#e11d48', border: 'rgba(244,63,94,0.25)' },
    EXPIRED: { bg: 'rgba(148,163,184,0.12)', text: '#64748b', border: 'rgba(148,163,184,0.25)' },
    QUEUED: { bg: 'rgba(59,130,246,0.12)', text: '#2563eb', border: 'rgba(59,130,246,0.25)' },
    EXITED: { bg: 'rgba(107,114,128,0.12)', text: '#4b5563', border: 'rgba(107,114,128,0.25)' },
    ENSEMBLE_FILTERED: { bg: 'rgba(217,119,6,0.12)', text: '#b45309', border: 'rgba(217,119,6,0.25)' },
  };

  const sideColors = {
    BUY: { bg: 'rgba(16,185,129,0.12)', text: '#059669' },
    SELL: { bg: 'rgba(244,63,94,0.12)', text: '#e11d48' },
  };

  const sourceColors = {
    CHARTINK: { bg: 'rgba(245,158,11,0.12)', text: '#d97706', border: 'rgba(245,158,11,0.25)' },
    INTERNAL: { bg: 'rgba(99,102,241,0.12)', text: '#4f46e5', border: 'rgba(99,102,241,0.25)' },
  };

  return (
    <div>
      {/* Header */}
      <div className="page-header-aurora" style={{ marginBottom: '32px' }}>
        <h1 style={{ fontSize: '32px', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '8px' }}>
          📡 Trading Signals
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '15px' }}>Real-time strategy signals generated by your active deployments</p>
      </div>

      {/* Stats */}
      <div className="stats-grid-aurora" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', marginBottom: '32px' }}>
        {statCards.map((card, i) => (
          <div key={i} className="card-aurora" style={{ padding: '24px', animationDelay: `${i * 100}ms` }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
              <span style={{ fontSize: '28px' }}>{card.icon}</span>
              <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: card.gradient }} />
            </div>
            <div style={{ fontSize: '28px', fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'JetBrains Mono, monospace', marginBottom: '4px' }}>
              <AnimatedCounter value={card.value} />
            </div>
            <div style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.8px' }}>{card.label}</div>
          </div>
        ))}
      </div>

      {/* Open Positions */}
      {positions.length > 0 && (
        <div className="card-aurora" style={{ padding: '24px', marginBottom: '24px', borderTop: '3px solid #10b981' }}>
          <h3 style={{ fontSize: '16px', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span>📈</span> Open Positions ({positions.length})
          </h3>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '16px' }}>
            {positions.map((pos) => (
              <div key={pos.id} style={{
                padding: '16px',
                borderRadius: '12px',
                background: 'rgba(16,185,129,0.06)',
                border: '1px solid rgba(16,185,129,0.15)',
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                  <span style={{ fontWeight: 800, fontFamily: 'JetBrains Mono, monospace', color: 'var(--text-primary)' }}>{pos.symbol}</span>
                  <span style={{
                    padding: '3px 8px',
                    borderRadius: '6px',
                    fontSize: '10px',
                    fontWeight: 800,
                    textTransform: 'uppercase',
                    background: pos.side === 'BUY' ? 'rgba(16,185,129,0.15)' : 'rgba(244,63,94,0.15)',
                    color: pos.side === 'BUY' ? '#059669' : '#e11d48',
                  }}>{pos.side}</span>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', fontSize: '12px', fontFamily: 'JetBrains Mono, monospace' }}>
                  <div><span style={{ color: 'var(--text-muted)' }}>Qty:</span> <strong style={{ color: 'var(--text-primary)' }}>{pos.quantity}</strong></div>
                  <div><span style={{ color: 'var(--text-muted)' }}>Entry:</span> <strong style={{ color: 'var(--text-primary)' }}>{Number(pos.entryPrice).toFixed(2)}</strong></div>
                  <div><span style={{ color: '#e11d48' }}>SL:</span> <strong>{Number(pos.stopLoss).toFixed(2)}</strong></div>
                  <div><span style={{ color: '#059669' }}>Tgt:</span> <strong>{Number(pos.target).toFixed(2)}</strong></div>
                </div>
                {pos.unrealizedPnl !== 0 && (
                  <div style={{ marginTop: '8px', fontSize: '12px', fontWeight: 700, color: pos.unrealizedPnl >= 0 ? '#059669' : '#e11d48', fontFamily: 'JetBrains Mono, monospace' }}>
                    PnL: {pos.unrealizedPnl >= 0 ? '+' : ''}{Number(pos.unrealizedPnl).toFixed(2)}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Search Box */}
      <div className="card-aurora" style={{ padding: '16px 20px', marginBottom: '16px' }}>
        <input
          type="text"
          placeholder="Search by symbol (e.g., WIPRO, RELIANCE)..."
          value={searchSymbol}
          onChange={(e) => setSearchSymbol(e.target.value)}
          style={{
            width: '100%',
            padding: '10px 14px',
            borderRadius: '10px',
            border: '1px solid rgba(148,163,184,0.25)',
            fontSize: '13px',
            color: 'var(--text-primary)',
            background: 'rgba(148,163,184,0.05)',
            outline: 'none',
            transition: 'all 0.2s',
          }}
          onFocus={(e) => { e.target.style.borderColor = 'rgba(99,102,241,0.5)'; e.target.style.background = 'rgba(99,102,241,0.03)'; }}
          onBlur={(e) => { e.target.style.borderColor = 'rgba(148,163,184,0.25)'; e.target.style.background = 'rgba(148,163,184,0.05)'; }}
        />
      </div>

      {/* Time Filter and Status Filter */}
      <div className="card-aurora" style={{ padding: '16px 20px', marginBottom: '24px' }}>
        <div style={{ marginBottom: '12px' }}>
          <span style={{ fontSize: '13px', fontWeight: 700, color: 'var(--text-muted)', marginRight: '8px' }}>Time:</span>
          {['ALL', 'TODAY', 'HISTORY'].map((tf) => (
            <button
              key={tf}
              onClick={() => setTimeFilter(tf)}
              style={{
                marginRight: '8px',
                padding: '6px 12px',
                borderRadius: '8px',
                border: 'none',
                fontSize: '11px',
                fontWeight: 700,
                cursor: 'pointer',
                textTransform: 'uppercase',
                letterSpacing: '0.4px',
                transition: 'all 0.2s',
                background: timeFilter === tf ? 'linear-gradient(135deg, #06b6d4, #3b82f6)' : 'rgba(148,163,184,0.1)',
                color: timeFilter === tf ? 'white' : 'var(--text-muted)',
              }}
            >
              {tf}
            </button>
          ))}
        </div>
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'center' }}>
          <span style={{ fontSize: '13px', fontWeight: 700, color: 'var(--text-muted)', marginRight: '8px' }}>Status:</span>
          {['ALL', 'GENERATED', 'EXECUTED', 'REJECTED', 'EXPIRED'].map((status) => (
            <button
              key={status}
              onClick={() => setFilter(status)}
              style={{
                padding: '8px 16px',
                borderRadius: '10px',
                border: 'none',
                fontSize: '12px',
                fontWeight: 700,
                cursor: 'pointer',
                textTransform: 'uppercase',
                letterSpacing: '0.5px',
                transition: 'all 0.2s',
                background: filter === status ? 'linear-gradient(135deg, #6366f1, #8b5cf6)' : 'rgba(148,163,184,0.1)',
                color: filter === status ? 'white' : 'var(--text-muted)',
              }}
            >
              {status === 'ALL' ? 'All Signals' : status}
            </button>
          ))}
          <span style={{ marginLeft: 'auto', fontSize: '13px', color: 'var(--text-muted)' }}>
            Showing <strong style={{ color: 'var(--text-primary)' }}>{filtered.length}</strong> of {signals.length}
          </span>
        </div>
      </div>

      {/* Signals Table */}
      <div className="card-aurora" style={{ padding: '24px', overflow: 'hidden' }}>
        {sigLoading ? (
          <div style={{ textAlign: 'center', padding: '60px', color: 'var(--text-muted)' }}>Loading signals...</div>
        ) : filtered.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: '48px', marginBottom: '16px' }}>📭</div>
            <div style={{ fontSize: '18px', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '8px' }}>No signals found</div>
            <div>Signals will appear here when your active deployments generate them.</div>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px', tableLayout: 'auto' }}>
              <colgroup>
                <col style={{ width: '150px' }} />
                <col style={{ width: '90px' }} />
                <col style={{ width: '120px' }} />
                <col style={{ width: '120px' }} />
                <col style={{ width: '120px' }} />
                <col style={{ width: '110px' }} />
                <col style={{ width: '150px' }} />
                <col style={{ width: '130px' }} />
                <col style={{ width: '110px' }} />
                <col style={{ width: '110px' }} />
              </colgroup>
              <thead style={{ backgroundColor: 'rgba(148,163,184,0.05)' }}>
                <tr style={{ borderBottom: '2px solid rgba(148,163,184,0.15)' }}>
                  <th style={{ textAlign: 'left', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Symbol</th>
                  <th style={{ textAlign: 'center', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Side</th>
                  <th style={{ textAlign: 'right', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Entry</th>
                  <th style={{ textAlign: 'right', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>SL</th>
                  <th style={{ textAlign: 'right', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Target</th>
                  <th style={{ textAlign: 'center', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Score</th>
                  <th style={{ textAlign: 'center', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Strategy</th>
                  <th style={{ textAlign: 'center', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Status</th>
                  <th style={{ textAlign: 'center', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Source</th>
                  <th style={{ textAlign: 'center', padding: '12px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Time</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((s, i) => (
                  <tr
                    key={`${s.id}-${i}`}
                    className="signal-row-aurora"
                    style={{
                      borderBottom: '1px solid rgba(148,163,184,0.08)',
                      animationDelay: `${i * 50}ms`,
                      transition: 'background 0.2s',
                    }}
                    onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(99,102,241,0.04)'; }}
                    onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; }}
                  >
                    <td style={{ padding: '12px', fontWeight: 700, color: 'var(--text-primary)', fontFamily: 'JetBrains Mono, monospace', overflow: 'hidden', textOverflow: 'ellipsis' }}>{s.symbol}</td>
                    <td style={{ padding: '12px', textAlign: 'center' }}>
                      <span style={{
                        padding: '3px 8px',
                        borderRadius: '6px',
                        fontSize: '10px',
                        fontWeight: 800,
                        textTransform: 'uppercase',
                        letterSpacing: '0.3px',
                        background: sideColors[s.side]?.bg || 'rgba(148,163,184,0.12)',
                        color: sideColors[s.side]?.text || '#64748b',
                        display: 'inline-block',
                        whiteSpace: 'nowrap',
                      }}>{s.side}</span>
                    </td>
                    <td style={{ padding: '12px', textAlign: 'right', fontFamily: 'JetBrains Mono, monospace', fontWeight: 600, color: 'var(--text-primary)', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {s.entryPrice ? Number(s.entryPrice).toFixed(2) : '—'}
                    </td>
                    <td style={{ padding: '12px', textAlign: 'right', fontFamily: 'JetBrains Mono, monospace', fontWeight: 600, color: '#e11d48', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {s.stopLoss ? Number(s.stopLoss).toFixed(2) : '—'}
                    </td>
                    <td style={{ padding: '12px', textAlign: 'right', fontFamily: 'JetBrains Mono, monospace', fontWeight: 600, color: '#059669', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {s.target ? Number(s.target).toFixed(2) : '—'}
                    </td>
                    <td style={{ padding: '12px', textAlign: 'center' }}>
                      {s.confidence != null ? (
                        <span style={{ fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, fontSize: '12px', color: Number(s.confidence) >= 80 ? '#10b981' : Number(s.confidence) >= 60 ? '#f59e0b' : '#ef4444' }}>
                          {Number(s.confidence).toFixed(0)}%
                        </span>
                      ) : (
                        <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>—</span>
                      )}
                    </td>
                    <td style={{ padding: '12px', textAlign: 'center', color: 'var(--text-secondary)', fontSize: '11px', overflow: 'hidden', textOverflow: 'ellipsis' }} title={s.reason}>
                      {s.reason || '—'}
                    </td>
                    <td style={{ padding: '12px', textAlign: 'center' }}>
                      <span style={{
                        padding: '3px 8px',
                        borderRadius: '6px',
                        fontSize: '9px',
                        fontWeight: 800,
                        textTransform: 'uppercase',
                        letterSpacing: '0.3px',
                        background: statusColors[s.status]?.bg || 'rgba(148,163,184,0.12)',
                        color: statusColors[s.status]?.text || '#64748b',
                        display: 'inline-block',
                        whiteSpace: 'nowrap',
                      }}>{s.status}</span>
                    </td>
                    <td style={{ padding: '12px', textAlign: 'center' }}>
                      <span style={{
                        padding: '3px 8px',
                        borderRadius: '6px',
                        fontSize: '9px',
                        fontWeight: 800,
                        textTransform: 'uppercase',
                        letterSpacing: '0.3px',
                        background: sourceColors[s.source]?.bg || 'rgba(148,163,184,0.12)',
                        color: sourceColors[s.source]?.text || '#64748b',
                        display: 'inline-block',
                        whiteSpace: 'nowrap',
                      }}>{s.source || 'INTERNAL'}</span>
                    </td>
                    <td style={{ padding: '12px', textAlign: 'center', color: 'var(--text-muted)', fontSize: '11px', fontFamily: 'JetBrains Mono, monospace', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {new Date(s.createdAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
