import { useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import client from '../api/client';

function AnimatedCounter({ value, duration = 1200 }) {
  const [display, setDisplay] = useState(0);
  useEffect(() => {
    let start = null;
    const animate = (ts) => {
      if (!start) start = ts;
      const p = Math.min((ts - start) / duration, 1);
      const eased = 1 - Math.pow(1 - p, 3);
      setDisplay(Math.floor(value * eased));
      if (p < 1) requestAnimationFrame(animate);
    };
    requestAnimationFrame(animate);
  }, [value, duration]);
  return <span>{display.toLocaleString('en-IN')}</span>;
}

export default function Signals() {
  const [filter, setFilter] = useState('ALL'); // ALL, GENERATED, EXECUTED, REJECTED, EXPIRED

  const { data: signals = [], isLoading: sigLoading } = useQuery({
    queryKey: ['signals'],
    queryFn: async () => {
      const res = await client.get('/signals');
      return res.data;
    },
  });

  const { data: stats = { total: 0, today: 0, active: 0 } } = useQuery({
    queryKey: ['signal-stats'],
    queryFn: async () => {
      const res = await client.get('/signals/stats');
      return res.data;
    },
  });

  const filtered = filter === 'ALL' ? signals : signals.filter(s => s.status === filter);

  const statCards = [
    { label: 'Total Signals', value: stats.total, icon: '📡', gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)' },
    { label: 'Today', value: stats.today, icon: '📅', gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)' },
    { label: 'Active', value: stats.active, icon: '⚡', gradient: 'linear-gradient(135deg, #10b981, #059669)' },
  ];

  const statusColors = {
    GENERATED: { bg: 'rgba(99,102,241,0.12)', text: '#4f46e5', border: 'rgba(99,102,241,0.25)' },
    EXECUTED: { bg: 'rgba(16,185,129,0.12)', text: '#059669', border: 'rgba(16,185,129,0.25)' },
    REJECTED: { bg: 'rgba(244,63,94,0.12)', text: '#e11d48', border: 'rgba(244,63,94,0.25)' },
    EXPIRED: { bg: 'rgba(148,163,184,0.12)', text: '#64748b', border: 'rgba(148,163,184,0.25)' },
  };

  const sideColors = {
    BUY: { bg: 'rgba(16,185,129,0.12)', text: '#059669' },
    SELL: { bg: 'rgba(244,63,94,0.12)', text: '#e11d48' },
  };

  const sourceColors = {
    CHARTINK: { bg: 'rgba(245,158,11,0.12)', text: '#d97706', border: 'rgba(245,158,11,0.25)' },
    INTERNAL: { bg: 'rgba(99,102,241,0.12)', text: '#4f46e5', border: 'rgba(99,102,241,0.25)' },
  };

  return (
    <div>
      {/* Header */}
      <div className="page-header-aurora" style={{ marginBottom: '32px' }}>
        <h1 style={{ fontSize: '32px', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '8px' }}>
          📡 Trading Signals
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '15px' }}>Real-time strategy signals generated by your active deployments</p>
      </div>

      {/* Stats */}
      <div className="stats-grid-aurora" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', marginBottom: '32px' }}>
        {statCards.map((card, i) => (
          <div key={i} className="card-aurora" style={{ padding: '24px', animationDelay: `${i * 100}ms` }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
              <span style={{ fontSize: '28px' }}>{card.icon}</span>
              <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: card.gradient }} />
            </div>
            <div style={{ fontSize: '28px', fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'JetBrains Mono, monospace', marginBottom: '4px' }}>
              <AnimatedCounter value={card.value} />
            </div>
            <div style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.8px' }}>{card.label}</div>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="card-aurora" style={{ padding: '16px 20px', marginBottom: '24px', display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'center' }}>
        <span style={{ fontSize: '13px', fontWeight: 700, color: 'var(--text-muted)', marginRight: '8px' }}>Filter:</span>
        {['ALL', 'GENERATED', 'EXECUTED', 'REJECTED', 'EXPIRED'].map((status) => (
          <button
            key={status}
            onClick={() => setFilter(status)}
            style={{
              padding: '8px 16px',
              borderRadius: '10px',
              border: 'none',
              fontSize: '12px',
              fontWeight: 700,
              cursor: 'pointer',
              textTransform: 'uppercase',
              letterSpacing: '0.5px',
              transition: 'all 0.2s',
              background: filter === status ? 'linear-gradient(135deg, #6366f1, #8b5cf6)' : 'rgba(148,163,184,0.1)',
              color: filter === status ? 'white' : 'var(--text-muted)',
            }}
          >
            {status === 'ALL' ? 'All Signals' : status}
          </button>
        ))}
        <span style={{ marginLeft: 'auto', fontSize: '13px', color: 'var(--text-muted)' }}>
          Showing <strong style={{ color: 'var(--text-primary)' }}>{filtered.length}</strong> of {signals.length}
        </span>
      </div>

      {/* Signals Table */}
      <div className="card-aurora" style={{ padding: '24px', overflow: 'hidden' }}>
        {sigLoading ? (
          <div style={{ textAlign: 'center', padding: '60px', color: 'var(--text-muted)' }}>Loading signals...</div>
        ) : filtered.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: '48px', marginBottom: '16px' }}>📭</div>
            <div style={{ fontSize: '18px', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '8px' }}>No signals found</div>
            <div>Signals will appear here when your active deployments generate them.</div>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
              <thead>
                <tr style={{ borderBottom: '2px solid rgba(148,163,184,0.15)' }}>
                  <th style={{ textAlign: 'left', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Symbol</th>
                  <th style={{ textAlign: 'left', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Side</th>
                  <th style={{ textAlign: 'right', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Entry</th>
                  <th style={{ textAlign: 'right', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>SL</th>
                  <th style={{ textAlign: 'right', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Target</th>
                  <th style={{ textAlign: 'center', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Mvt Score</th>
                  <th style={{ textAlign: 'left', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Scanner</th>
                  <th style={{ textAlign: 'center', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Status</th>
                  <th style={{ textAlign: 'center', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Source</th>
                  <th style={{ textAlign: 'right', padding: '12px 16px', color: 'var(--text-muted)', fontWeight: 700, fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Time</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((s, i) => (
                  <tr
                    key={s.id}
                    className="signal-row-aurora"
                    style={{
                      borderBottom: '1px solid rgba(148,163,184,0.08)',
                      animationDelay: `${i * 50}ms`,
                      transition: 'background 0.2s',
                    }}
                    onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(99,102,241,0.04)'; }}
                    onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; }}
                  >
                    <td style={{ padding: '14px 16px', fontWeight: 700, color: 'var(--text-primary)', fontFamily: 'JetBrains Mono, monospace' }}>{s.symbol}</td>
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{
                        padding: '4px 10px',
                        borderRadius: '8px',
                        fontSize: '11px',
                        fontWeight: 800,
                        textTransform: 'uppercase',
                        letterSpacing: '0.5px',
                        background: sideColors[s.side]?.bg || 'rgba(148,163,184,0.12)',
                        color: sideColors[s.side]?.text || '#64748b',
                      }}>{s.side}</span>
                    </td>
                    <td style={{ padding: '14px 16px', textAlign: 'right', fontFamily: 'JetBrains Mono, monospace', fontWeight: 600, color: 'var(--text-primary)' }}>
                      {s.entryPrice ? Number(s.entryPrice).toFixed(2) : '—'}
                    </td>
                    <td style={{ padding: '14px 16px', textAlign: 'right', fontFamily: 'JetBrains Mono, monospace', fontWeight: 600, color: '#e11d48' }}>
                      {s.stopLoss ? Number(s.stopLoss).toFixed(2) : '—'}
                    </td>
                    <td style={{ padding: '14px 16px', textAlign: 'right', fontFamily: 'JetBrains Mono, monospace', fontWeight: 600, color: '#059669' }}>
                      {s.target ? Number(s.target).toFixed(2) : '—'}
                    </td>
                    <td style={{ padding: '14px 16px', textAlign: 'center' }}>
                      {s.movementScore != null ? (
                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}>
                          <div style={{ width: '40px', height: '4px', borderRadius: '2px', background: 'rgba(148,163,184,0.2)', overflow: 'hidden' }}>
                            <div style={{ width: `${Math.min(s.movementScore, 100)}%`, height: '100%', borderRadius: '2px', background: s.movementScore >= 70 ? '#10b981' : s.movementScore >= 50 ? '#f59e0b' : '#ef4444' }} />
                          </div>
                          <span style={{ fontSize: '11px', fontWeight: 700, fontFamily: 'JetBrains Mono, monospace', color: 'var(--text-muted)' }}>{s.movementScore.toFixed(1)}</span>
                        </div>
                      ) : (
                        <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>—</span>
                      )}
                    </td>
                    <td style={{ padding: '14px 16px', color: 'var(--text-secondary)', fontSize: '12px', maxWidth: '140px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={s.scannerName}>
                      {s.scannerName || '—'}
                    </td>
                    <td style={{ padding: '14px 16px', textAlign: 'center' }}>
                      <span style={{
                        padding: '4px 10px',
                        borderRadius: '8px',
                        fontSize: '10px',
                        fontWeight: 800,
                        textTransform: 'uppercase',
                        letterSpacing: '0.5px',
                        background: statusColors[s.status]?.bg || 'rgba(148,163,184,0.12)',
                        color: statusColors[s.status]?.text || '#64748b',
                        border: `1px solid ${statusColors[s.status]?.border || 'rgba(148,163,184,0.2)'}`,
                      }}>{s.status}</span>
                    </td>
                    <td style={{ padding: '14px 16px', textAlign: 'center' }}>
                      <span style={{
                        padding: '4px 10px',
                        borderRadius: '8px',
                        fontSize: '10px',
                        fontWeight: 800,
                        textTransform: 'uppercase',
                        letterSpacing: '0.5px',
                        background: sourceColors[s.source]?.bg || 'rgba(148,163,184,0.12)',
                        color: sourceColors[s.source]?.text || '#64748b',
                        border: `1px solid ${sourceColors[s.source]?.border || 'rgba(148,163,184,0.2)'}`,
                      }}>{s.source || 'INTERNAL'}</span>
                    </td>
                    <td style={{ padding: '14px 16px', textAlign: 'right', color: 'var(--text-muted)', fontSize: '11px', fontFamily: 'JetBrains Mono, monospace' }}>
                      {new Date(s.createdAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
