server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: stokr-v5
  jackson:
    time-zone: Asia/Kolkata
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  flyway:
    enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    root: INFO
    com.stokr: INFO
