package com.stokr.marketdata.integrity;

public enum IntegrityRejectionReason {
    CROSS_SESSION_LOOKBACK,
    TIMESTAMP_GAP_EXCEEDED,
    INSUFFICIENT_SESSION_BARS,
    NIFTY_OPENING_INCOMPLETE,
    EQUITY_CANDLE_STALE,
    INDEX_CANDLE_STALE,
    TICK_FEED_STALE,
    SESSION_BOUNDARY_NOT_FOUND,
    STRATEGY_DISABLED_INTEGRITY
}
